name: 伟哥
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '1 */2 * * *'
jobs:
  build:
    runs-on: macos-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/Github-Yo/Actions.git ~/Actions
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x          
      - name: npm install
        run: |
          cd ~/Actions      
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
          
          
      - name: '【伟哥】'
        run: |  
          cd ~/Actions/Task
          node youthshare.js    
